apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kasmass808/argocd-helm.git
    targetRevision: main
    path: helm-charts/nginx
    helm:
      valueFiles:
        - values/minikube.yaml
      parameters:
        - name: replicaCount
          value: "1"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
